# Generated by Django 2.0.3 on 2018-04-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quesdtion',
            new_name='question',
        ),
    ]
